"""Turn the difference between two weekly runs into a list of events.

The site is refreshed every Monday and nothing recorded what moved. This module
diffs the current run against the previous snapshot and writes one entry per
run into data/changelog.json, which the landing card and feed.xml both read.

What counts as an event is the whole design problem here. Two rules keep the
feed worth subscribing to:

  * A change is only reported when both sides of the comparison are known. Old
    snapshots predate half these fields, and "licence changed from nothing to
    MIT" is an artefact of the schema, not news.
  * A rank move has to clear a threshold on rank *and* on score. Models a
    tenth of a point apart trade places on normalization noise every few weeks;
    reporting that would bury the weeks something real happened.

Anything derived from citing records asks when the tracker first saw them
(`first_seen`, stamped in build_data.py), not when the paper was published. A
2024 paper OpenAlex indexed last Tuesday is news to this site the week it
arrives, and its publication date would file it under a week nobody is reading.
"""
import config


def _model_index(rows):
    return dict((r["id"], r) for r in rows)


def _prev_models(previous):
    return (previous or {}).get("models", {})


def _both(prev, cur, key):
    """Previous and current value of a field, or None if either is missing.

    A field absent from the older snapshot is unknown, not changed. Every
    comparison below goes through here so a schema addition cannot manufacture
    an event for all 19 models on the week it lands.
    """
    if prev is None or cur is None:
        return None
    a, b = prev.get(key), cur.get(key)
    if a is None or b is None:
        return None
    return (a, b)


def _event(kind, text, models=None, url=None):
    ev = {"type": kind, "text": text}
    if models:
        ev["models"] = models
    if url:
        ev["url"] = url
    return ev


def _licence(value):
    """NOASSERTION is what the GitHub API returns for a repo with no recognised
    licence file. The site renders that as "unclear" rather than shouting an API
    constant at the reader, and the changelog matches."""
    return "unstated" if (value or "").upper() in ("", "NOASSERTION") else value


def _plural(n, word):
    return "{} {}{}".format(n, word, "" if n == 1 else "s")


def _dedupe_versions(records):
    """Collapse the reviewed-preprint versions OpenAlex stores as separate works.

    "Benchmarking biochemical networks generated by large language models" is
    four records: the bioRxiv preprint and three eLife reviewed versions, each
    with its own work id and DOI. Announcing it once a week as each version is
    indexed is precisely the noise that gets a feed unsubscribed, so the
    changelog keys on the normalized title and merges the models covered.

    This only governs what is announced. Citation totals elsewhere on the site
    still count every work id, which is a separate question from what belongs
    in a weekly digest.
    """
    out = []
    by_title = {}
    for rec in records:
        key = "".join(ch for ch in (rec.get("title") or "").lower() if ch.isalnum())
        if not key:
            out.append(rec)
            continue
        first = by_title.get(key)
        if first is None:
            by_title[key] = rec
            out.append(rec)
            continue
        merged = [m for m in rec.get("models", []) if m not in first.get("models", [])]
        first.setdefault("models", []).extend(merged)
    return out


def build(rows, previous, h2h, prev_h2h, new_records, today_iso, baseline):
    """One changelog entry for today's run.

    rows         scored model rows, already ranked
    previous     the previous history.json snapshot, or None
    h2h          today's head-to-head output
    prev_h2h     the head-to-head file from the previous run, or None
    new_records  citing records first seen in this run, with the models each covers
    baseline     True on the first run after this feature lands, which suppresses
                 every "new" event -- on that run the whole corpus is new, and a
                 feed entry listing 4,747 papers is noise, not a changelog.
    """
    cur = _model_index(rows)
    prev = _prev_models(previous)
    events = []

    if baseline:
        events.append(_event(
            "baseline",
            "Change tracking starts here: {} models and {} citations on record. "
            "From the next refresh this entry lists what moved.".format(
                len(rows), "{:,}".format(sum(r["citations"] for r in rows)))))
        return {"date": today_iso, "baseline": True, "events": events}

    # ---- models entering the registry --------------------------------------
    for row in rows:
        if row["id"] in prev:
            continue
        events.append(_event(
            "model_added",
            "{} joins the tracker — {} paper, {}, entering at #{}.".format(
                row["name"], row["year"],
                _plural("{:,}".format(row["citations"]), "citation")
                if row["citations"] != 1 else "1 citation",
                row["rank"]),
            [row["id"]]))

    # ---- rank moves ---------------------------------------------------------
    for row in rows:
        pair = _both(prev.get(row["id"]), row, "rank")
        scores = _both(prev.get(row["id"]), row, "score")
        if not pair or not scores:
            continue
        moved = pair[0] - pair[1]          # positive = climbed toward #1
        if abs(moved) < config.RANK_MOVE_MIN:
            continue
        if abs(scores[1] - scores[0]) < config.SCORE_MOVE_MIN:
            continue
        events.append(_event(
            "rank_move",
            "{} {} {} to #{} (score {}, {}{}).".format(
                row["name"],
                "climbs" if moved > 0 else "falls",
                _plural(abs(moved), "place"),
                pair[1], scores[1],
                "+" if scores[1] >= scores[0] else "",
                round(scores[1] - scores[0], 1)),
            [row["id"]]))

    # ---- upkeep and licence -------------------------------------------------
    PHRASE = {
        "archived": "has been archived by its authors",
        "dormant": "has gone dormant — no commit in over a year",
        "slowing": "has slowed — no commit in over 90 days",
        "active": "is being actively developed again",
    }
    for row in rows:
        pair = _both(prev.get(row["id"]), row, "upkeep")
        if not pair or pair[0] == pair[1]:
            continue
        phrase = PHRASE.get(pair[1])
        if not phrase:
            continue
        events.append(_event(
            "upkeep", "{}'s repository {}.".format(row["name"], phrase), [row["id"]]))

    for row in rows:
        pair = _both(prev.get(row["id"]), row, "license")
        if not pair or pair[0] == pair[1]:
            continue
        events.append(_event(
            "license",
            "{}'s licence changed from {} to {}.".format(
                row["name"], _licence(pair[0]), _licence(pair[1])),
            [row["id"]]))

    # ---- citation milestones ------------------------------------------------
    for row in rows:
        pair = _both(prev.get(row["id"]), row, "citations")
        if not pair:
            continue
        for mark in config.CITATION_MILESTONES:
            if pair[0] < mark <= pair[1]:
                events.append(_event(
                    "milestone",
                    "{} passes {:,} citations.".format(row["name"], mark),
                    [row["id"]]))

    # ---- benchmarking papers that arrived this week -------------------------
    # The label the whole site is built around: a new evaluation is the one
    # citing paper worth interrupting someone's week for. Applications are
    # counted, not listed.
    new_records = _dedupe_versions(new_records)
    bench = [r for r in new_records if r.get("use") == "benchmark"]
    for rec in bench[:config.CHANGELOG_MAX_PAPERS]:
        covers = [cur[m]["name"] for m in rec.get("models", []) if m in cur]
        events.append(_event(
            "benchmark_paper",
            "“{}” ({}){}.".format(
                rec.get("title") or "untitled",
                rec.get("venue") or "unlisted",
                " — covers " + ", ".join(covers) if covers else ""),
            rec.get("models", []),
            rec.get("doi")))
    if len(bench) > config.CHANGELOG_MAX_PAPERS:
        events.append(_event(
            "benchmark_paper",
            "…and {} further benchmarking paper{}.".format(
                len(bench) - config.CHANGELOG_MAX_PAPERS,
                "" if len(bench) - config.CHANGELOG_MAX_PAPERS == 1 else "s")))

    others = len(new_records) - len(bench)
    if others > 0:
        events.append(_event(
            "citing", "{} newly indexed, none of them evaluations.".format(
                _plural(others, "other citing paper"))))

    # ---- first joint evaluation of a pair -----------------------------------
    # Zero to non-zero on a head-to-head cell is the moment two models stopped
    # being incomparable, which no other view on the site announces.
    if prev_h2h:
        old = prev_h2h.get("pairs", {})
        for key, cell in sorted(h2h.get("pairs", {}).items()):
            if not cell.get("bench"):
                continue
            if old.get(key, {}).get("bench"):
                continue
            ids = key.split("|")
            if not all(i in cur for i in ids):
                continue
            events.append(_event(
                "first_comparison",
                "First joint evaluation of {} and {}.".format(
                    cur[ids[0]]["name"], cur[ids[1]]["name"]),
                ids))

    return {"date": today_iso, "events": events}


def append(existing, entry):
    """Add today's entry, replacing any entry already written for today.

    A same-day rerun -- a manual workflow_dispatch after a failure -- should
    correct the day's entry rather than publish it twice, which would give the
    feed two entries with the same id.
    """
    entries = [e for e in (existing or {}).get("entries", [])
               if e.get("date") != entry["date"]]
    entries.append(entry)
    entries.sort(key=lambda e: e["date"])
    return {"entries": entries[-config.CHANGELOG_WEEKS:]}
